### ISSUE TITLE
Postgres: Inserting data into an array column of int8range causes RS adapter restart loop

### ISSUE THREAD

**Issue by readyset-railway** [readysettech/readyset#281]
### Description

This only happens if the column is an array. If it's the column is just a "`int8range`", the write is ignored with "`Ignoring write with value of unsupported type type_oid=3926 schema="public" table="t"`".

### Steps to reproduce 

```
create table t(r int8range[]);
insert into t values (array[int8range(1,2)]);
```

### ReadySet version

a878c8a07cce8d62b0bab7ed5f77d696cd02e6f3

### Upstream DB type and version

PostgreSQL 15.3

### Logs

```
2023-07-24T14:37:04.814498Z  WARN connection{addr=127.0.0.1:53456}:query: readyset_adapter::backend: Error received from noria, sending query to fallback error=Query failed to parse: create table t(r int8range[]);
2023-07-24T14:37:05.035905Z  WARN replicators::noria_adapter: Restarting adapter after error encountered error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range"))
2023-07-24T14:37:05.035925Z ERROR replicators: Error in replication, will retry after timeout error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range")) timeout_sec=1
2023-07-24T14:37:06.051154Z  INFO replicators::postgres_connector::ddl_replication: Setting up DDL replication
2023-07-24T14:37:06.051809Z  INFO tokio_postgres::connection: NOTICE: schema "readyset" already exists, skipping
2023-07-24T14:37:06.058985Z  INFO replicators::postgres_connector::ddl_replication: Set up DDL replication
2023-07-24T14:37:06.063714Z  INFO replicators::noria_adapter: Connected to PostgreSQL
2023-07-24T14:37:06.067859Z  INFO replicators::noria_adapter: Streaming replication started
2023-07-24T14:37:06.068208Z  WARN replicators::noria_adapter: Restarting adapter after error encountered error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range"))
2023-07-24T14:37:06.068226Z ERROR replicators: Error in replication, will retry after timeout error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range")) timeout_sec=1
2023-07-24T14:37:07.083325Z  INFO replicators::postgres_connector::ddl_replication: Setting up DDL replication
2023-07-24T14:37:07.084020Z  INFO tokio_postgres::connection: NOTICE: schema "readyset" already exists, skipping
2023-07-24T14:37:07.093181Z  INFO replicators::postgres_connector::ddl_replication: Set up DDL replication
2023-07-24T14:37:07.097940Z  INFO replicators::noria_adapter: Connected to PostgreSQL
2023-07-24T14:37:07.102030Z  INFO replicators::noria_adapter: Streaming replication started
2023-07-24T14:37:07.102396Z  WARN replicators::noria_adapter: Restarting adapter after error encountered error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range"))
2023-07-24T14:37:07.102413Z ERROR replicators: Error in replication, will retry after timeout error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range")) timeout_sec=1
2023-07-24T14:37:08.116288Z  INFO replicators::postgres_connector::ddl_replication: Setting up DDL replication
2023-07-24T14:37:08.117284Z  INFO tokio_postgres::connection: NOTICE: schema "readyset" already exists, skipping
2023-07-24T14:37:08.124957Z  INFO replicators::postgres_connector::ddl_replication: Set up DDL replication
2023-07-24T14:37:08.130374Z  INFO replicators::noria_adapter: Connected to PostgreSQL
2023-07-24T14:37:08.135745Z  INFO replicators::noria_adapter: Streaming replication started
2023-07-24T14:37:08.136062Z  WARN replicators::noria_adapter: Restarting adapter after error encountered error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range"))
2023-07-24T14:37:08.136085Z ERROR replicators: Error in replication, will retry after timeout error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range")) timeout_sec=1
2023-07-24T14:37:09.151620Z  INFO replicators::postgres_connector::ddl_replication: Setting up DDL replication
2023-07-24T14:37:09.152471Z  INFO tokio_postgres::connection: NOTICE: schema "readyset" already exists, skipping
2023-07-24T14:37:09.160349Z  INFO replicators::postgres_connector::ddl_replication: Set up DDL replication
2023-07-24T14:37:09.165015Z  INFO replicators::noria_adapter: Connected to PostgreSQL
2023-07-24T14:37:09.169129Z  INFO replicators::noria_adapter: Streaming replication started
2023-07-24T14:37:09.169612Z  WARN replicators::noria_adapter: Restarting adapter after error encountered error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range"))
2023-07-24T14:37:09.169631Z ERROR replicators: Error in replication, will retry after timeout error=Error during replication: WAL error: ReadySetError(Unsupported("Unsupported type: int8range")) timeout_sec=1
```

**Comment by frannoriega** [comment]
It seems like this bug got fixed at some point, since I couldn't reproduce it on our current `main` branch (commit `761d57771fa2a2bb2cb32c04af04e9a9bfddada7` at the moment of writing this).

**Comment by readyset-railway** [comment]
I can still reproduce this issue. Perhaps it's related to the OS? I'm running OSX 13.4.1 on Intel Core i9.

**Comment by lukoktonos** [comment]
Was also able to reproduce on m1 mac

**Comment by lukoktonos** [comment]
It looks like we need to convert the `into_noria_vec()?` in wal_reader.rs to `into_noria_vec().ok_or_else(|| WalError::TableError {`

so that this error is converted to a TableError, which we handle by filtering out tables with unsupported types.

Unless there is another way to support `int8range[]` fully--but we should probably convert the error either way.
